### ISSUE TITLE
Changes needed for update to Godot 3.2

### ISSUE THREAD

**Issue by rubenjavier** [GDQuest/godot-make-pro-2d-games#107]
Hi,
to make the project work on Godot 3.2 the function "assert" now need parenthesis for its arguments
For example in the file:
core/world/Door.gd

assert map_path != ""
must now be:
assert(map_path != "")

The List where this must be done is bellow (it needs to be done in two .tscn files, not just in .gd files, just open them in a text editor and find "assert")

actors/CoinsFountain.tscn
core/save/SaveAndLoad.gd
core/shop/Shop.gd
core/world/Door.gd
interface/menus/inventory/InventoryMenu.gd
interface/menus/pause/PauseMenu.gd
interface/menus/shop/ShopMenu.gd
interface/menus/shop/menus/ShopSubMenu.gd
interface/menus/shop/popups/AmountPopup.gd
levels/Cave.tscn
monsters/bosses/wild_boar/states/Die.gd
monsters/bosses/wild_boar/states/Spawn.gd

**Comment by NathanLovato** [comment]
I already did this locally, thought I had pushed it

**Comment by rubenjavier** [comment]
Thanks as usual Nathan, 
no it wasnt  ;)

**Comment by NathanLovato** [comment]
Done
